name: Run R script

on:
  push:
    branches:
      - master  # Change this to your main branch name
  pull_request:
    branches:
      - master  # Change this to your main branch name

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    

    steps:

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.x'

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("nnet"), repos="https://cloud.r-project.org/")'

    - name: Run R script
      run: Rscript mlp.R
      
    